Rafactoring + more tests
Circlegain/exchanges pull request #17
Opened 2020-10-21 07:25 UTC by catena2w

2020-10-21 17:25 UTC, eanea requested changes

2020-10-21 17:25 UTC, eanea commented on src/main/scala/com/circlegain/exchanges/binance/rest/BinancePrivateRestClient.scala
> +      .filter(_.totalBalance > 0)
add showZeroBalances

2020-10-22 09:52 UTC, catena2w commented on src/main/scala/com/circlegain/exchanges/binance/rest/BinancePrivateRestClient.scala
> +      .filter(_.totalBalance > 0)
fixed

2020-10-22 15:39 UTC, eanea commented on src/main/scala/com/circlegain/exchanges/binance/rest/BinancePrivateRestClient.scala
> +      .filter(b => showZeroBalances || BigDecimal(b._2.getTotal) > 0)
I think should be >= 0

2020-10-22 15:42 UTC, eanea requested changes

2020-10-22 15:42 UTC, eanea commented on src/main/scala/com/circlegain/exchanges/core/rest/AuthenticatedRestExchange.scala
> +      requestedBalance.getOrElse(Balance(ts, token, 0, 0))
It's incorrect. You return zero balance, even such balance doesn't exist on the server.

2020-10-27 06:54 UTC, merged